# 线性代数实现

In [1]:
#导入第三方库
import torch


In [3]:
#标量由只有一个元素的张量组成
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x + y, x*y, x / y, x - y, x**y #指数运算 

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([1.]), tensor([9.]))

In [5]:
#向量可视为标量值组成的列表,可以通过索引来访问任意值
x = torch.arange(4)
print(x[3])
x.shape

tensor(3)


torch.Size([4])

In [8]:
#通过指定两个分量m，n来创建一个形状为m*n的矩阵
A = torch.arange(20).reshape(5, 4)
print(A)
#矩阵A的转置矩阵
A.T

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
#对称矩阵A等于其转置矩阵
B = torch.tensor([[1, 2, 3],
                  [2, 0, 4],
                  [3, 4, 5]])
#判断矩阵B是否和自己的转置矩阵相等
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
#向量是标量的推广，矩阵是向量的推广，我们可以构建具有更多轴的数据结构
X = torch.arange(24).reshape(2, 3, 4)
X 

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
#给定具有相同形状的任何两个张量，任何按元素二元运算的结果都是相同形状的张量
A = torch.arange(20).reshape(5, 4)
B = A.clone() #通过分配新内存将A的副本分配给B
A.shape == (A+B).shape

True

In [13]:
#两个矩阵按元素乘法称为哈达玛积
A * B

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [14]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a* X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [15]:
#计算矩阵元素的和
x = torch.arange(4, dtype= torch.float32)
x.sum()

tensor(6.)

In [24]:
#表示任意形状张量的和
A = torch.arange(40, dtype= torch.float32).reshape(2, 5, 4)
print(A)
#指定汇总张量的轴
A_sum_axis0 = A.sum(axis= 0)
print(A_sum_axis0)
A_sum_axis1 = A.sum(axis= 1)
print(A_sum_axis1)
A_sum_axis2 = A.sum(axis= 2)
print(A_sum_axis2)
#按维度组合汇总张量
print(A.sum(axis= [0, 1]))

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])
tensor([[20., 22., 24., 26.],
        [28., 30., 32., 34.],
        [36., 38., 40., 42.],
        [44., 46., 48., 50.],
        [52., 54., 56., 58.]])
tensor([[ 40.,  45.,  50.,  55.],
        [140., 145., 150., 155.]])
tensor([[  6.,  22.,  38.,  54.,  70.],
        [ 86., 102., 118., 134., 150.]])
tensor([180., 190., 200., 210.])


In [28]:
#一个与求和相关的量是平均值(mean或average)
A.mean(), A.sum()/ A.numel()
#指定维度求平均
A.mean(axis = 0), A.sum(axis= 0) / A.shape[0]
#计算总和或均值时保持轴数不变,设置keepdims参数为True
sum_A = A.sum(axis = 1, keepdims= True)
print(sum_A)
#通过广播机制将A除以sum_A
A / sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])


tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [30]:
#按某个轴计算A元素的累积总和
print(A.cumsum(axis= 0))

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])


In [32]:
#点积是相同位置按元素乘积的和
y = torch.ones(4, dtype= torch.float32)
#可以通过执行按元素乘法，然后进行元素求和来表示两个向量的点积
print(torch.sum(x*y))
x, y, torch.dot(x, y)

tensor(6.)


(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [33]:
#矩阵向量积Ax是一个长度为m的列向量
A = A.reshape(10, 4)
torch.mv(A, x)

tensor([ 14.,  38.,  62.,  86., 110., 134., 158., 182., 206., 230.])

In [34]:
#我们可以将矩阵-矩阵乘法AB看作是简单地执行m次矩阵-向量积并将结果拼接在一起，形成一个n*m的矩阵
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[  6.,   6.,   6.],
        [ 22.,  22.,  22.],
        [ 38.,  38.,  38.],
        [ 54.,  54.,  54.],
        [ 70.,  70.,  70.],
        [ 86.,  86.,  86.],
        [102., 102., 102.],
        [118., 118., 118.],
        [134., 134., 134.],
        [150., 150., 150.]])

In [37]:
#L2范数是向量元素平方和的平方根，方法为torch.norm()
u = torch.tensor([3.0, -4.0])
print(torch.norm(u))
#L1范数表示为向量元素的绝对值之和
print(torch.abs(u).sum())
#矩阵的费罗贝尼乌斯范数(Frobenius norm)是矩阵元素平方和的平方根
print(torch.norm(torch.ones((4,9))))

tensor(5.)
tensor(7.)
tensor(6.)
